run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - unused
    - ineffassign
    - misspell
    - gofmt
    - goimports
    - bodyclose
    - nilerr

linters-settings:
  goimports:
    local-prefixes: github.com/example/freeradius-operator
  govet:
    enable-all: false

issues:
  exclude-dirs:
    - testdata
  exclude-generated: strict
