package renderer

import (
	"bytes"
	"fmt"
)

const defaultShardMaxBytes = 800 * 1024 // 800KB, well under 1MB etcd limit

// renderClients renders the main clients.conf with localhost entries and $INCLUDE directives
// for sharded client files.
func renderClients(clients []ClientSpec, shardCount int) (string, error) {
	type clientsContext struct {
		ShardCount int
	}
	var buf bytes.Buffer
	if err := tmpl.ExecuteTemplate(&buf, "clients.conf.tmpl", clientsContext{ShardCount: shardCount}); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// renderClientShard renders a single shard of client definitions.
func renderClientShard(clients []ClientSpec) (string, error) {
	var buf bytes.Buffer
	if err := tmpl.ExecuteTemplate(&buf, "clients_shard.tmpl", clients); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// shardClients splits clients into shards, each fitting within maxBytes when rendered.
// Returns the shards as slices of ClientSpec.
func shardClients(clients []ClientSpec, maxBytes int) ([][]ClientSpec, error) {
	if len(clients) == 0 {
		return [][]ClientSpec{{}}, nil
	}
	if maxBytes <= 0 {
		maxBytes = defaultShardMaxBytes
	}

	var shards [][]ClientSpec
	var current []ClientSpec
	currentSize := 0
	headerSize := len("# clients shard — generated by freeradius-operator\n# DO NOT EDIT MANUALLY\n\n")

	for _, c := range clients {
		// Estimate rendered size per client (~150 bytes typical)
		rendered := fmt.Sprintf("client %s {\n    ipaddr = %s\n    secret = ${file:/etc/freeradius/secrets/%s/%s}\n    nastype = %s\n}\n\n",
			c.Name, c.IP, c.SecretRef.Name, c.SecretRef.Key, c.NASType)
		entrySize := len(rendered)

		if currentSize+entrySize+headerSize > maxBytes && len(current) > 0 {
			shards = append(shards, current)
			current = nil
			currentSize = 0
		}
		current = append(current, c)
		currentSize += entrySize
	}

	if len(current) > 0 {
		shards = append(shards, current)
	}

	return shards, nil
}
