package renderer

import (
	"bytes"
	"fmt"
	"text/template"
)

var clientTmpl = template.Must(template.New("client").Parse(`client {{ .Name }} {
    ipaddr = {{ .IP }}
    secret = $${file:/etc/freeradius/secrets/{{ .SecretRef.Name }}/{{ .SecretRef.Key }}}
    nastype = {{ .NASType }}
}
`))

func renderClients(clients []ClientSpec) (string, error) {
	var buf bytes.Buffer
	buf.WriteString("# clients.conf — generated by freeradius-operator\n# DO NOT EDIT MANUALLY\n\n")
	buf.WriteString("client localhost {\n    ipaddr = 127.0.0.1\n    secret = testing123\n    nastype = other\n}\n\n")

	for _, c := range clients {
		if err := clientTmpl.Execute(&buf, c); err != nil {
			return "", fmt.Errorf("rendering client %q: %w", c.Name, err)
		}
		buf.WriteByte('\n')
	}
	return buf.String(), nil
}
