package renderer

import (
	"bytes"
	"text/template"
)

var radiusdTmpl = template.Must(template.New("radiusd.conf").Parse(`# radiusd.conf — generated by freeradius-operator
# DO NOT EDIT MANUALLY

status_server = yes

$INCLUDE clients.conf
$INCLUDE mods-enabled/
$INCLUDE sites-enabled/

listen {
    type = auth
    ipaddr = *
    port = 1812
}

listen {
    type = acct
    ipaddr = *
    port = 1813
}
`))

func renderRadiusd(cluster ClusterSpec) (string, error) {
	var buf bytes.Buffer
	if err := radiusdTmpl.Execute(&buf, cluster); err != nil {
		return "", err
	}
	return buf.String(), nil
}
