package renderer

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
)

// validStages is the ordered list of valid FreeRADIUS processing stages.
var validStages = []string{
	"authorize",
	"authenticate",
	"preacct",
	"accounting",
	"post-auth",
	"pre-proxy",
	"post-proxy",
	"session",
}

var validStageSet = func() map[string]bool {
	m := make(map[string]bool, len(validStages))
	for _, s := range validStages {
		m[s] = true
	}
	return m
}()

// renderSites renders the sites-enabled/default virtual server file.
func renderSites(policies []PolicySpec) (string, error) {
	// Validate all stages and action types first
	for _, p := range policies {
		if !validStageSet[p.Stage] {
			return "", &InvalidStageError{Stage: p.Stage}
		}
		for _, a := range p.Actions {
			switch a.Type {
			case "set", "call", "reject", "accept":
				// valid
			default:
				return "", &InvalidActionError{ActionType: a.Type}
			}
		}
	}

	// Group policies by stage
	byStage := make(map[string][]PolicySpec)
	for _, p := range policies {
		byStage[p.Stage] = append(byStage[p.Stage], p)
	}

	// Sort each stage group by priority ascending
	for stage := range byStage {
		sort.Slice(byStage[stage], func(i, j int) bool {
			return byStage[stage][i].Priority < byStage[stage][j].Priority
		})
	}

	var buf bytes.Buffer
	buf.WriteString("# sites-enabled/default — generated by freeradius-operator\n# DO NOT EDIT MANUALLY\n\n")
	buf.WriteString("server default {\n")

	for _, stage := range validStages {
		fmt.Fprintf(&buf, "    %s {\n", stage)
		for _, p := range byStage[stage] {
			renderPolicy(&buf, p, "        ")
		}
		buf.WriteString("    }\n")
	}

	buf.WriteString("}\n")
	return buf.String(), nil
}

// renderPolicy renders a single policy as an unlang if block.
func renderPolicy(buf *bytes.Buffer, p PolicySpec, indent string) {
	// Build condition string
	cond := buildCondition(p.Match)

	fmt.Fprintf(buf, "%s# priority %d: %s\n", indent, p.Priority, p.Name)
	if cond != "" {
		fmt.Fprintf(buf, "%sif (%s) {\n", indent, cond)
	} else {
		fmt.Fprintf(buf, "%sif (true) {\n", indent)
	}

	for _, action := range p.Actions {
		renderAction(buf, action, indent+"    ")
	}

	fmt.Fprintf(buf, "%s}\n", indent)
}

// buildCondition builds an unlang condition string from a PolicyMatch.
// All three combinator types (All, Any, None) are composed together with &&.
func buildCondition(match *PolicyMatch) string {
	if match == nil {
		return ""
	}

	var groups []string

	// all: conditions joined with &&
	if len(match.All) > 0 {
		wrapped := make([]string, len(match.All))
		for i, leaf := range match.All {
			wrapped[i] = fmt.Sprintf("(%s %s %s)", leaf.Attribute, leaf.Operator, leaf.Value)
		}
		if len(wrapped) == 1 {
			groups = append(groups, wrapped[0])
		} else {
			groups = append(groups, "("+strings.Join(wrapped, " && ")+")")
		}
	}

	// any: conditions joined with ||
	if len(match.Any) > 0 {
		wrapped := make([]string, len(match.Any))
		for i, leaf := range match.Any {
			wrapped[i] = fmt.Sprintf("(%s %s %s)", leaf.Attribute, leaf.Operator, leaf.Value)
		}
		if len(wrapped) == 1 {
			groups = append(groups, wrapped[0])
		} else {
			groups = append(groups, "("+strings.Join(wrapped, " || ")+")")
		}
	}

	// none: conditions negated and joined with &&
	if len(match.None) > 0 {
		wrapped := make([]string, len(match.None))
		for i, leaf := range match.None {
			wrapped[i] = fmt.Sprintf("!(%s %s %s)", leaf.Attribute, leaf.Operator, leaf.Value)
		}
		if len(wrapped) == 1 {
			groups = append(groups, wrapped[0])
		} else {
			groups = append(groups, "("+strings.Join(wrapped, " && ")+")")
		}
	}

	if len(groups) == 0 {
		return ""
	}
	if len(groups) == 1 {
		return groups[0]
	}
	return strings.Join(groups, " && ")
}

// renderAction renders a single policy action.
func renderAction(buf *bytes.Buffer, action PolicyAction, indent string) {
	switch action.Type {
	case "set":
		fmt.Fprintf(buf, "%supdate reply {\n%s    %s := \"%s\"\n%s}\n", indent, indent, action.Attribute, action.Value, indent)
	case "call":
		fmt.Fprintf(buf, "%s%s\n", indent, action.Module)
	case "reject":
		fmt.Fprintf(buf, "%sreject\n", indent)
	case "accept":
		fmt.Fprintf(buf, "%sok\n", indent)
	}
}
