package renderer

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
)

var validStages = []string{
	"authorize", "authenticate", "preacct", "accounting",
	"post-auth", "pre-proxy", "post-proxy", "session",
}

var validStageSet = func() map[string]bool {
	m := make(map[string]bool, len(validStages))
	for _, s := range validStages {
		m[s] = true
	}
	return m
}()

func renderSites(policies []PolicySpec) (string, error) {
	for _, p := range policies {
		if !validStageSet[p.Stage] {
			return "", &InvalidStageError{Stage: p.Stage}
		}
		for _, a := range p.Actions {
			switch a.Type {
			case "set", "call", "reject", "accept":
			default:
				return "", &InvalidActionError{ActionType: a.Type}
			}
		}
	}

	byStage := make(map[string][]PolicySpec)
	for _, p := range policies {
		byStage[p.Stage] = append(byStage[p.Stage], p)
	}
	for stage := range byStage {
		sort.Slice(byStage[stage], func(i, j int) bool {
			return byStage[stage][i].Priority < byStage[stage][j].Priority
		})
	}

	var buf bytes.Buffer
	buf.WriteString("# sites-enabled/default — generated by freeradius-operator\n# DO NOT EDIT MANUALLY\n\n")
	buf.WriteString("server default {\n")
	for _, stage := range validStages {
		fmt.Fprintf(&buf, "    %s {\n", stage)
		for _, p := range byStage[stage] {
			renderPolicy(&buf, p, "        ")
		}
		buf.WriteString("    }\n")
	}
	buf.WriteString("}\n")
	return buf.String(), nil
}

func renderPolicy(buf *bytes.Buffer, p PolicySpec, indent string) {
	cond := buildCondition(p.Match)
	fmt.Fprintf(buf, "%s# priority %d: %s\n", indent, p.Priority, p.Name)
	if cond == "" {
		cond = "true"
	}
	fmt.Fprintf(buf, "%sif (%s) {\n", indent, cond)
	for _, action := range p.Actions {
		renderAction(buf, action, indent+"    ")
	}
	fmt.Fprintf(buf, "%s}\n", indent)
}

func buildCondition(match *PolicyMatch) string {
	if match == nil {
		return ""
	}

	var groups []string

	if len(match.All) > 0 {
		groups = append(groups, joinLeaves(match.All, " && ", false))
	}
	if len(match.Any) > 0 {
		groups = append(groups, joinLeaves(match.Any, " || ", false))
	}
	if len(match.None) > 0 {
		groups = append(groups, joinLeaves(match.None, " && ", true))
	}

	switch len(groups) {
	case 0:
		return ""
	case 1:
		return groups[0]
	default:
		return strings.Join(groups, " && ")
	}
}

func joinLeaves(leaves []MatchLeaf, sep string, negate bool) string {
	wrapped := make([]string, len(leaves))
	for i, leaf := range leaves {
		expr := fmt.Sprintf("(%s %s %s)", leaf.Attribute, leaf.Operator, leaf.Value)
		if negate {
			expr = "!" + expr
		}
		wrapped[i] = expr
	}
	if len(wrapped) == 1 {
		return wrapped[0]
	}
	return "(" + strings.Join(wrapped, sep) + ")"
}

func renderAction(buf *bytes.Buffer, action PolicyAction, indent string) {
	switch action.Type {
	case "set":
		fmt.Fprintf(buf, "%supdate reply {\n%s    %s := \"%s\"\n%s}\n", indent, indent, action.Attribute, action.Value, indent)
	case "call":
		fmt.Fprintf(buf, "%s%s\n", indent, action.Module)
	case "reject":
		fmt.Fprintf(buf, "%sreject\n", indent)
	case "accept":
		fmt.Fprintf(buf, "%sok\n", indent)
	}
}
