apiVersion: radius.operator.io/v1alpha1
kind: RadiusCluster
metadata:
  name: my-radius-files
  namespace: default
spec:
  image: freeradius/freeradius-server:3.2.3
  replicas: 1
  modules:
    - name: files
      type: rlm_files
      enabled: true
      files:
        authorize: |
          bob  Cleartext-Password := "hello"
               Reply-Message := "Hello, %{User-Name}"

          alice  Cleartext-Password := "welcome"
                 Service-Type := Framed-User,
                 Framed-Protocol := PPP
    - name: pap
      type: rlm_pap
      enabled: true
