apiVersion: radius.operator.io/v1alpha1
kind: RadiusClient
metadata:
  name: edge-routers
  namespace: default
spec:
  clusterRef: split-radius
  ip: 172.16.0.0/12
  secretRef:
    name: nas-secret
    key: shared-secret
  nasType: juniper
