apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
stringData:
  password: "dbP@ssw0rd"
---
apiVersion: v1
kind: Secret
metadata:
  name: nas-secret
  namespace: default
type: Opaque
stringData:
  shared-secret: "NasR@diusKey"
