//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingConfig) DeepCopyInto(out *AutoscalingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingConfig.
func (in *AutoscalingConfig) DeepCopy() *AutoscalingConfig {
	if in == nil {
		return nil
	}
	out := new(AutoscalingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoAConfig) DeepCopyInto(out *CoAConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoAConfig.
func (in *CoAConfig) DeepCopy() *CoAConfig {
	if in == nil {
		return nil
	}
	out := new(CoAConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilesConfig) DeepCopyInto(out *FilesConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilesConfig.
func (in *FilesConfig) DeepCopy() *FilesConfig {
	if in == nil {
		return nil
	}
	out := new(FilesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EAPConfig) DeepCopyInto(out *EAPConfig) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(EAPTLSConfig)
		**out = **in
	}
	if in.TTLS != nil {
		in, out := &in.TTLS, &out.TTLS
		*out = new(EAPTTLSConfig)
		**out = **in
	}
	if in.PEAP != nil {
		in, out := &in.PEAP, &out.PEAP
		*out = new(EAPPEAPConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EAPConfig.
func (in *EAPConfig) DeepCopy() *EAPConfig {
	if in == nil {
		return nil
	}
	out := new(EAPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EAPPEAPConfig) DeepCopyInto(out *EAPPEAPConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EAPPEAPConfig.
func (in *EAPPEAPConfig) DeepCopy() *EAPPEAPConfig {
	if in == nil {
		return nil
	}
	out := new(EAPPEAPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EAPTLSConfig) DeepCopyInto(out *EAPTLSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EAPTLSConfig.
func (in *EAPTLSConfig) DeepCopy() *EAPTLSConfig {
	if in == nil {
		return nil
	}
	out := new(EAPTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EAPTTLSConfig) DeepCopyInto(out *EAPTTLSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EAPTTLSConfig.
func (in *EAPTTLSConfig) DeepCopy() *EAPTTLSConfig {
	if in == nil {
		return nil
	}
	out := new(EAPTTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPConfig) DeepCopyInto(out *LDAPConfig) {
	*out = *in
	out.PasswordRef = in.PasswordRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPConfig.
func (in *LDAPConfig) DeepCopy() *LDAPConfig {
	if in == nil {
		return nil
	}
	out := new(LDAPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchLeaf) DeepCopyInto(out *MatchLeaf) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchLeaf.
func (in *MatchLeaf) DeepCopy() *MatchLeaf {
	if in == nil {
		return nil
	}
	out := new(MatchLeaf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleConfig) DeepCopyInto(out *ModuleConfig) {
	*out = *in
	if in.SQL != nil {
		in, out := &in.SQL, &out.SQL
		*out = new(SQLConfig)
		**out = **in
	}
	if in.LDAP != nil {
		in, out := &in.LDAP, &out.LDAP
		*out = new(LDAPConfig)
		**out = **in
	}
	if in.EAP != nil {
		in, out := &in.EAP, &out.EAP
		*out = new(EAPConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.REST != nil {
		in, out := &in.REST, &out.REST
		*out = new(RESTConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Redis != nil {
		in, out := &in.Redis, &out.Redis
		*out = new(RedisConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = new(FilesConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleConfig.
func (in *ModuleConfig) DeepCopy() *ModuleConfig {
	if in == nil {
		return nil
	}
	out := new(ModuleConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDBConfig) DeepCopyInto(out *PDBConfig) {
	*out = *in
	if in.MinAvailable != nil {
		in, out := &in.MinAvailable, &out.MinAvailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDBConfig.
func (in *PDBConfig) DeepCopy() *PDBConfig {
	if in == nil {
		return nil
	}
	out := new(PDBConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAction) DeepCopyInto(out *PolicyAction) {
	*out = *in
	if in.Modules != nil {
		in, out := &in.Modules, &out.Modules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAction.
func (in *PolicyAction) DeepCopy() *PolicyAction {
	if in == nil {
		return nil
	}
	out := new(PolicyAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyMatch) DeepCopyInto(out *PolicyMatch) {
	*out = *in
	if in.All != nil {
		in, out := &in.All, &out.All
		*out = make([]MatchLeaf, len(*in))
		copy(*out, *in)
	}
	if in.Any != nil {
		in, out := &in.Any, &out.Any
		*out = make([]MatchLeaf, len(*in))
		copy(*out, *in)
	}
	if in.None != nil {
		in, out := &in.None, &out.None
		*out = make([]MatchLeaf, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyMatch.
func (in *PolicyMatch) DeepCopy() *PolicyMatch {
	if in == nil {
		return nil
	}
	out := new(PolicyMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbesConfig) DeepCopyInto(out *ProbesConfig) {
	*out = *in
	if in.Liveness != nil {
		in, out := &in.Liveness, &out.Liveness
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.Readiness != nil {
		in, out := &in.Readiness, &out.Readiness
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbesConfig.
func (in *ProbesConfig) DeepCopy() *ProbesConfig {
	if in == nil {
		return nil
	}
	out := new(ProbesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RESTConfig) DeepCopyInto(out *RESTConfig) {
	*out = *in
	if in.PasswordRef != nil {
		in, out := &in.PasswordRef, &out.PasswordRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.Authorize != nil {
		in, out := &in.Authorize, &out.Authorize
		*out = new(RESTStageConfig)
		**out = **in
	}
	if in.Authenticate != nil {
		in, out := &in.Authenticate, &out.Authenticate
		*out = new(RESTStageConfig)
		**out = **in
	}
	if in.Preacct != nil {
		in, out := &in.Preacct, &out.Preacct
		*out = new(RESTStageConfig)
		**out = **in
	}
	if in.Accounting != nil {
		in, out := &in.Accounting, &out.Accounting
		*out = new(RESTStageConfig)
		**out = **in
	}
	if in.PostAuth != nil {
		in, out := &in.PostAuth, &out.PostAuth
		*out = new(RESTStageConfig)
		**out = **in
	}
	if in.PreProxy != nil {
		in, out := &in.PreProxy, &out.PreProxy
		*out = new(RESTStageConfig)
		**out = **in
	}
	if in.PostProxy != nil {
		in, out := &in.PostProxy, &out.PostProxy
		*out = new(RESTStageConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RESTConfig.
func (in *RESTConfig) DeepCopy() *RESTConfig {
	if in == nil {
		return nil
	}
	out := new(RESTConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RESTStageConfig) DeepCopyInto(out *RESTStageConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RESTStageConfig.
func (in *RESTStageConfig) DeepCopy() *RESTStageConfig {
	if in == nil {
		return nil
	}
	out := new(RESTStageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadiusClient) DeepCopyInto(out *RadiusClient) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadiusClient.
func (in *RadiusClient) DeepCopy() *RadiusClient {
	if in == nil {
		return nil
	}
	out := new(RadiusClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RadiusClient) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadiusClientList) DeepCopyInto(out *RadiusClientList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RadiusClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadiusClientList.
func (in *RadiusClientList) DeepCopy() *RadiusClientList {
	if in == nil {
		return nil
	}
	out := new(RadiusClientList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RadiusClientList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadiusClientSpec) DeepCopyInto(out *RadiusClientSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadiusClientSpec.
func (in *RadiusClientSpec) DeepCopy() *RadiusClientSpec {
	if in == nil {
		return nil
	}
	out := new(RadiusClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadiusClientStatus) DeepCopyInto(out *RadiusClientStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadiusClientStatus.
func (in *RadiusClientStatus) DeepCopy() *RadiusClientStatus {
	if in == nil {
		return nil
	}
	out := new(RadiusClientStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadiusCluster) DeepCopyInto(out *RadiusCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadiusCluster.
func (in *RadiusCluster) DeepCopy() *RadiusCluster {
	if in == nil {
		return nil
	}
	out := new(RadiusCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RadiusCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadiusClusterList) DeepCopyInto(out *RadiusClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RadiusCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadiusClusterList.
func (in *RadiusClusterList) DeepCopy() *RadiusClusterList {
	if in == nil {
		return nil
	}
	out := new(RadiusClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RadiusClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadiusClusterSpec) DeepCopyInto(out *RadiusClusterSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(AutoscalingConfig)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		**out = **in
	}
	if in.Probes != nil {
		in, out := &in.Probes, &out.Probes
		*out = new(ProbesConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Modules != nil {
		in, out := &in.Modules, &out.Modules
		*out = make([]ModuleConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PDB != nil {
		in, out := &in.PDB, &out.PDB
		*out = new(PDBConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]v1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ServiceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = new(ServicesConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CoA != nil {
		in, out := &in.CoA, &out.CoA
		*out = new(CoAConfig)
		**out = **in
	}
	if in.Radiusd != nil {
		in, out := &in.Radiusd, &out.Radiusd
		*out = new(RadiusdConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.InitResources != nil {
		in, out := &in.InitResources, &out.InitResources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadiusClusterSpec.
func (in *RadiusClusterSpec) DeepCopy() *RadiusClusterSpec {
	if in == nil {
		return nil
	}
	out := new(RadiusClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadiusClusterStatus) DeepCopyInto(out *RadiusClusterStatus) {
	*out = *in
	if in.ExternalIPs != nil {
		in, out := &in.ExternalIPs, &out.ExternalIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadiusClusterStatus.
func (in *RadiusClusterStatus) DeepCopy() *RadiusClusterStatus {
	if in == nil {
		return nil
	}
	out := new(RadiusClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadiusPolicy) DeepCopyInto(out *RadiusPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadiusPolicy.
func (in *RadiusPolicy) DeepCopy() *RadiusPolicy {
	if in == nil {
		return nil
	}
	out := new(RadiusPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RadiusPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadiusPolicyList) DeepCopyInto(out *RadiusPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RadiusPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadiusPolicyList.
func (in *RadiusPolicyList) DeepCopy() *RadiusPolicyList {
	if in == nil {
		return nil
	}
	out := new(RadiusPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RadiusPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadiusPolicySpec) DeepCopyInto(out *RadiusPolicySpec) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = new(PolicyMatch)
		(*in).DeepCopyInto(*out)
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]PolicyAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadiusPolicySpec.
func (in *RadiusPolicySpec) DeepCopy() *RadiusPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RadiusPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadiusPolicyStatus) DeepCopyInto(out *RadiusPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadiusPolicyStatus.
func (in *RadiusPolicyStatus) DeepCopy() *RadiusPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(RadiusPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadiusdConfig) DeepCopyInto(out *RadiusdConfig) {
	*out = *in
	if in.Log != nil {
		in, out := &in.Log, &out.Log
		*out = new(RadiusdLogConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(RadiusdSecurityConfig)
		**out = **in
	}
	if in.ThreadPool != nil {
		in, out := &in.ThreadPool, &out.ThreadPool
		*out = new(RadiusdThreadPool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadiusdConfig.
func (in *RadiusdConfig) DeepCopy() *RadiusdConfig {
	if in == nil {
		return nil
	}
	out := new(RadiusdConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadiusdLogConfig) DeepCopyInto(out *RadiusdLogConfig) {
	*out = *in
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(bool)
		**out = **in
	}
	if in.AuthBadpass != nil {
		in, out := &in.AuthBadpass, &out.AuthBadpass
		*out = new(bool)
		**out = **in
	}
	if in.AuthGoodpass != nil {
		in, out := &in.AuthGoodpass, &out.AuthGoodpass
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadiusdLogConfig.
func (in *RadiusdLogConfig) DeepCopy() *RadiusdLogConfig {
	if in == nil {
		return nil
	}
	out := new(RadiusdLogConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadiusdSecurityConfig) DeepCopyInto(out *RadiusdSecurityConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadiusdSecurityConfig.
func (in *RadiusdSecurityConfig) DeepCopy() *RadiusdSecurityConfig {
	if in == nil {
		return nil
	}
	out := new(RadiusdSecurityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadiusdThreadPool) DeepCopyInto(out *RadiusdThreadPool) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadiusdThreadPool.
func (in *RadiusdThreadPool) DeepCopy() *RadiusdThreadPool {
	if in == nil {
		return nil
	}
	out := new(RadiusdThreadPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisConfig) DeepCopyInto(out *RedisConfig) {
	*out = *in
	if in.PasswordRef != nil {
		in, out := &in.PasswordRef, &out.PasswordRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisConfig.
func (in *RedisConfig) DeepCopy() *RedisConfig {
	if in == nil {
		return nil
	}
	out := new(RedisConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQLConfig) DeepCopyInto(out *SQLConfig) {
	*out = *in
	out.PasswordRef = in.PasswordRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQLConfig.
func (in *SQLConfig) DeepCopy() *SQLConfig {
	if in == nil {
		return nil
	}
	out := new(SQLConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConfig) DeepCopyInto(out *ServiceConfig) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConfig.
func (in *ServiceConfig) DeepCopy() *ServiceConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpointConfig) DeepCopyInto(out *ServiceEndpointConfig) {
	*out = *in
	in.ServiceConfig.DeepCopyInto(&out.ServiceConfig)
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(AutoscalingConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpointConfig.
func (in *ServiceEndpointConfig) DeepCopy() *ServiceEndpointConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicesConfig) DeepCopyInto(out *ServicesConfig) {
	*out = *in
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(ServiceEndpointConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Accounting != nil {
		in, out := &in.Accounting, &out.Accounting
		*out = new(ServiceEndpointConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CoA != nil {
		in, out := &in.CoA, &out.CoA
		*out = new(ServiceEndpointConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicesConfig.
func (in *ServicesConfig) DeepCopy() *ServicesConfig {
	if in == nil {
		return nil
	}
	out := new(ServicesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}
