apiVersion: v1
kind: Secret
metadata:
  name: db-primary-credentials
  namespace: default
type: Opaque
stringData:
  password: "PrimaryDbP@ss"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-replica-credentials
  namespace: default
type: Opaque
stringData:
  password: "ReplicaDbP@ss"
---
apiVersion: v1
kind: Secret
metadata:
  name: switch-secret
  namespace: default
type: Opaque
stringData:
  shared-secret: "SwitchR@diusKey"
