apiVersion: v1
kind: Secret
metadata:
  name: ldap-bind-credentials
  namespace: default
type: Opaque
stringData:
  password: "LdapBindP@ss"
---
apiVersion: v1
kind: Secret
metadata:
  name: switch-secret
  namespace: default
type: Opaque
stringData:
  shared-secret: "SwitchR@diusKey"
